AllCops:
  TargetRubyVersion: 3.2.2
  SuggestExtensions: false
  NewCops: disable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

Metrics/AbcSize:
  Enabled: true
  Max: 15

Metrics/MethodLength:
  Enabled: false

Style/BlockDelimiters:
  Enabled: true

Layout/LineLength:
  Max: 120
